### ISSUE TITLE
Поддержка и публикация версий

### ISSUE THREAD

**Issue by kybarg** [skokov3812/encrypted-smiley-secure-protocol#10]
Хотим использовать этот пакет в своём решении для терминалов на Node.js
Хотелось бы периодических релизов и поддержки репозитория.
Могу взять поддержку на себя или помогать. Спасибо!

**Comment by skokov3812** [comment]
Это отличный вариант, т.к. библиотека была написана для разового проекта и доступа к оборудованию более нет, в этой связи поддержка становиться весьма затруднительной.
