### ISSUE TITLE
I get this warning regarding random-prime package...

### ISSUE THREAD

**Issue by adamfrost839** [skokov3812/encrypted-smiley-secure-protocol#11]
Warning: require() of ES modules is not supported.
require() of /opt/storage/appdir/node_modules/random-prime/index.js from /opt/storage/appdir/node_modules/encrypted-smiley-secure-protocol/index.js is an ES module file as it is a .js
 file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /opt/storage/appdir/node_modules/random-prime/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /opt/storage/appdir/no
de_modules/random-prime/package.json.

**Comment by skokov3812** [comment]
What version of node, npm are you using?

**Comment by adamfrost839** [comment]
npm -v
6.12.1

node -v
v12.13.1

pm2 -v
2.7.1
