### ISSUE TITLE
Event VALUE_ADDED not detected

### ISSUE THREAD

**Issue by iagolobla** [skokov3812/encrypted-smiley-secure-protocol#20]
Hi,

Using the SMART Hopper I noticed when I insert a coin, the poll command doesn't retrieve any event but checking the packet, the protocol do retrieve the VALUE_ADDED event. I guess it's pending to implement in the module.

Greetings and Great Job,
Iago Loureiro.

**Comment by kybarg** [comment]
@iagolobla was fixed with #27
