### ISSUE TITLE
Sequence Count get random value when connected to 2 devices

### ISSUE THREAD

**Issue by iagolobla** [skokov3812/encrypted-smiley-secure-protocol#22]
I have 2 devices connected with the module. Each one has an object with a different port. They should work separately, however, after a while with both devices enabled, one of them start getting sequence count numbers (like ACKs) totally random (even negative numbers) so the communication fails.

Also, if I duplicate the module locally and use each copy for each device it works perfectly. I guess there's some kind of interference.

Thank you for this module and keep working. Nice work!
Best Regards,
Iago Loureiro.

**Comment by kybarg** [comment]
@iagolobla I guess thi si related to global event emitter 
https://github.com/skokov3812/encrypted-smiley-secure-protocol/blob/master/src/index.js#L11
