### ISSUE TITLE
nv11 not accepting with example

### ISSUE THREAD

**Issue by kronicali** [skokov3812/encrypted-smiley-secure-protocol#23]
Hi, I am testing with nv11.
I ran the example, it says enabled 'OK' however the bezel does not light up to accept bills. I am able to run the Payout Last note with success and it dispenses but the Payout Amount function returns Command_NOT_KNOWN.

Any help will be great, thanks in advance.

**Comment by kronicali** [comment]
Already did this thanks got enabled to work, also is it that some commands are not able to work with nv11?  PAYOUT_NOTE works but not other payout commands.

**Comment by MrSugarCandy** [comment]
As you said only PAYOUT_NOTE works with NV11. 
You can see here:
https://innovative-technology.com/images/pdocuments/manuals/SSP_Manual.pdf 
Just go to NV11 command table.

**Comment by kronicali** [comment]
I realized this after digging into the source code here, You have been good help  sir. I guess I will have to roll my own way of managing those functions for the nv11.
