### ISSUE TITLE
unit_type: undefined

### ISSUE THREAD

**Issue by chandi61** [skokov3812/encrypted-smiley-secure-protocol#36]
hi, i have smart hopper and when i set the comand : setup_request

  success: true,
  status: 'OK',
  command: 'SETUP_REQUEST',
  info: {
    unit_type: undefined,
    firmware_version: '1.25',
    country_code: 'EUR',
    value_multiplier: 60801,
    channel_value: Uint8Array(0) [],
    channel_security: Uint8Array(0) [],
    real_value_multiplier: 131077,
    protocol_version: 0

some one can help me thanks

**Comment by kybarg** [comment]
@chandi61 pelase provide debug value for repsonse
