### ISSUE TITLE
Crash on COIN_CREDIT

### ISSUE THREAD

**Issue by drJeckyll** [skokov3812/encrypted-smiley-secure-protocol#38]
I have a Smart hopper and everything seems to work, until I insert a coin. 
Then i receive a crash in utils.js and I was able to track it to this piece of code: https://github.com/skokov3812/encrypted-smiley-secure-protocol/blob/master/src/utils.js#L376
Error is something like "out of bounds". Looking at chunk variable mine is: 
```
Uint8Array(8) [
  223, 200,  0,  0,
    0,  66, 71, 78
]

```
Having: `let count = chunk[1];` make next slices to go out of bounds, since there is clearly no 200 items into array. 
I can see that `200, 0, 0, 0` is value of coin I insert (200 stotinki), and next is `66, 71, 78` which is BGN. 
These values are not from 2 to 6 and from 6 to 9 like in: https://github.com/skokov3812/encrypted-smiley-secure-protocol/blob/master/src/utils.js#L380, but are offset by one i.e. from 1 to 5 and from 5 to 8.
Now the question is: is `chunk` wrong or there is something else what I miss?

**Comment by kybarg** [comment]
@drJeckyll could you please provide full message reveived?

**Comment by EduardKarnaukh** [comment]
[electron]     at new NodeError (node:internal/errors:371:5)
[electron]     at boundsError (node:internal/buffer:84:11)
[electron]     at Buffer.readInt32LE (node:internal/buffer:390:5)
[electron]     at parseData (/home/haircut/terminal/node_modules/encrypted-smiley-secure-protocol/src/utils.js:380:77)
[electron]     at SSP.parsePacket (/home/haircut/terminal/node_modules/encrypted-smiley-secure-protocol/src/index.js:219:24)
[electron]     at EventEmitter.<anonymous> (/home/haircut/terminal/node_modules/encrypted-smiley-secure-protocol/src/index.js:173:24)
[electron]     at Object.onceWrapper (node:events:646:26)
[electron]     at EventEmitter.emit (node:events:526:28)
[electron]     at ESSPProtocolParser.<anonymous> (/home/haircut/terminal/node_modules/encrypted-smiley-secure-protocol/src/index.js:59:27)
[electron]     at ESSPProtocolParser.emit (node:events:526:28)
[electron] (node:6359) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by kybarg** [comment]
@drJeckyll it can be protocol version issue
