### ISSUE TITLE
CRASH ON NOTE INSERTION

### ISSUE THREAD

**Issue by pazDontExist** [skokov3812/encrypted-smiley-secure-protocol#43]
hi, sorry to bother. 

But whenver i try to insert a banknote the software crash. with no errors 

Any idea ?

the hardware is an nv9usb+

**Comment by kybarg** [comment]
@pazDontExist you mean it exists rigth away?

**Comment by pazDontExist** [comment]
yes

**Comment by kybarg** [comment]
@pazDontExist could you try wraping your code in `try...catch``
and add at the and of your app
```javascript
process
  .on('unhandledRejection', (reason, promise) => {
    promise.catch((error) => {
      console.error('unhandledRejection', error)
    })
  })
  .on('uncaughtException', (error) => {
    console.error('uncaughtException', error)
  })

```

**Comment by pazDontExist** [comment]
you want also the trace-warnings ?

**Comment by kybarg** [comment]
@pazDontExist from this seems like error is in `example.js`
