### ISSUE TITLE
Automated releases

### ISSUE THREAD

**Issue by kybarg** [skokov3812/encrypted-smiley-secure-protocol#46]
Hi @skokov3812! 
I see that you are not very active in development of this project. Would be nce if you could allow automated releases using [semantic-release](https://github.com/semantic-release/semantic-release) and [Circle CI](https://circleci.com/) when changes are made to the main branch. Another option to add me as contributor on NPM or transfer repository to me, or public organization at github.
I appreciate your investment in this project! Thanks

**Comment by skokov3812** [comment]
@kybarg You have the same username on NPM?
Added you as a contributor on NPM
