### ISSUE TITLE
NV9USB+, would not enable after power down 

### ISSUE THREAD

**Issue by touy** [skokov3812/encrypted-smiley-secure-protocol#52]
I have implemented the software to monitor the NV9USB+, it seems to work perfectly, 
Open and sync per your example, it was installed on windows 10  ( nodejs)
1 I restarted and after could work normally 
2 if I shut it down, my code could not enable the device
3 if power is lost, my code could not enable the device.
==> so I have to use the C# sample application to open the connection to the device and enable it , and after I enable it via C# code, there would not be such a problem until the computer was shut down or power lost.

It seems the device could not be properly connected,  after 2 and 3 conditions.

Does any one have such a problem?

**Comment by touy** [comment]
getSequence() {
    this.sequence = this.sequence === 0x00 ? 0x80 : 0x00;
    return this.id | this.sequence;
  }
  
  maybe it's a wrong sequence number ? but why it could start and keep running since the C# program start

**Comment by kybarg** [comment]
@touy does it open port connnection?

**Comment by touy** [comment]
> @touy does it open port connnection?

I have figured out 
1. in my node code , I didn't set : this.eSSP.command('SET_CHANNEL_INHIBITS', { channels: process.env.channels||[1, 1, 1, 1, 1, 1, 1] })
- it was working for a while when I used a program from windows to initialize and  it seems it was a caching issue, 
- then I use my node to connect, and it would keep working for a while ( it seems about the hardware issue)
- now i have set SET_CHANNEL_INHIBITS, then it could work normally 

2. another issues, it is NV9, it seems my suppliers don't want to update the firmware as there are many new bills, since 2020

**Comment by kybarg** [comment]
@touy you can update it yourself from official website https://innovative-technology.com/support/secure-download
just create free account
We use ITL Validator Manager to update devices
