### ISSUE TITLE
SET_DENOMINATION_ROUTE return PARAMETER_OUT_OF_RANGE

### ISSUE THREAD

**Issue by DioneLago** [skokov3812/encrypted-smiley-secure-protocol#58]
Hi,
When sending the SET_DENOMINATION_ROUTE command with the following parameters in protocol version 6, the error PARAMETER_OUT_OF_RANGE is returned

parameters send:
{route: 'payout', value: 2000, country_code: 'EUR'}

Does anyone know what can it be ?

**Comment by DioneLago** [comment]
Problem solved...
I'm using an NV200 + Smart Payout.

In my case what was happening was that the Trusted Mode switch was not enabled. So I performed the process and it worked correctly, I believe that by default the hardware did not have key 0x0123456701234567 set.

**Comment by Hexagon-77** [comment]
> Problem solved...
> I'm using an NV200 + Smart Payout.
> 
> In my case what was happening was that the Trusted Mode switch was not enabled. So I performed the process and it worked correctly, I believe that by default the hardware did not have key 0x0123456701234567 set.

I'm having the same problem with my unit. How do I enable trusted mode? I've looked everywhere in the docs but I can't find it :/

**Comment by DioneLago** [comment]
Hi @Hexagon-77 ,
I got help through support from the manufacturer, they were quick and provided an effective solution.
You need to perform a reset with this tool https://bit.ly/itl-resetkey that they provided me so that the encrypted on is done and the code here in the library is recognized. To do this, simply connect Payout directly to a Windows PC and update with this program.

I hope it helps.
