### ISSUE TITLE
Spectral recycler

### ISSUE THREAD

**Issue by mathoso** [skokov3812/encrypted-smiley-secure-protocol#59]
hello,
new device https://innovative-technology.com/products/products-main/901-nv4000 is now available, with new commands and events. Is there some library update planned?

I tried some changes, but for this new device I have too much TIMEOUT responses while polling, and also device change status to DISABLED in some strange intervals, maybe because of timeouts.

**Comment by kybarg** [comment]
@mathoso please try my for and tell if it helps
https://github.com/kybarg/encrypted-smiley-secure-protocol

**Comment by mathoso** [comment]
@kybarg thank you, I already found @keepkey\encrypted-smiley-secure-protocol, which is working better, also I made some changes to work with Spectral device (adding some new commands, and events for smart emptying, repleniching, etc)
